language: php

php:
  - 7.0
  - 7.1

matrix:
  allow_failures:
  - php: 7.1

sudo: false

before_install:
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit
